//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p_tasks
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int task_id { get; set; }
        public Nullable<int> users_id { get; set; }
        public string title { get; set; }
        public string descriptions { get; set; }
        public string statues { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
    
        public virtual user user { get; set; }
    }
}
